In [18]:
import matplotlib.pyplot as plt
import numpy as np

x_np = np.linspace(0, 10, 1000)
y_np = 2 * np.sin(x_np) * np.cos(x_np)
# plt.plot(x_np, y_np)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import jax.numpy as jnp

x_jnp = jnp.linspace(0, 10, 1000)
y_jnp = 2 * jnp.sin(x_jnp) * jnp.cos(x_jnp)
plt.plot(x_jnp, y_jnp)

In [14]:
x = np.arange(10)
print(x)
x[0] = 10
print(x)

x = jnp.arange(10)
print(x)
# x[0] = 10
y = x.at[0].set(10)
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[10  1  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[10  1  2  3  4  5  6  7  8  9]


In [ ]:
import jax.numpy as jnp
jnp.add(1, 1.0)  # jax.numpy API implicitly promotes mixed types.
from jax import lax
lax.add(1, 1.0)  # jax.lax API requires explicit type promotion.

In [19]:
x = np.array([1, 2, 1])
y = np.ones(10)
np.convolve(x, y)

array([1., 3., 4., 4., 4., 4., 4., 4., 4., 4., 3., 1.])

In [27]:
from jax import jit
@jit
def f(x, y):
  print("Running f():")
  print(f"  x = {x}")
  print(f"  y = {y}")
  result = jnp.dot(x + 1, y + 1)
  print(f"  result = {result}")
  return result

x = np.random.randn(3, 4)
y = np.random.randn(4)
print(x)
print(y)
f(x, y)
# print(result.shape)

[[-0.96211952 -1.49932107 -0.4211677   0.64748899]
 [ 1.00984     0.45534519  0.26355762  0.09083976]
 [-0.31524434 -0.44052481 -1.71060737 -0.48899574]]
[ 0.69114754 -0.11198041 -0.92202481  0.2910646 ]
Running f():
  x = Traced<ShapedArray(float32[3,4])>with<DynamicJaxprTrace(level=1/0)>
  y = Traced<ShapedArray(float32[4])>with<DynamicJaxprTrace(level=1/0)>
  result = Traced<ShapedArray(float32[3])>with<DynamicJaxprTrace(level=1/0)>


Array([1.792804 , 6.1981816, 2.2591777], dtype=float32)

In [28]:
x2 = np.random.randn(3, 4)
y2 = np.random.randn(4)
f(x2, y2)

Array([10.174366,  3.642298,  2.438101], dtype=float32)